server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Если файл не найден, перенаправляем на index.html (для React Router)
        try_files $uri $uri/ /index.html;
    }

}