# Generated by Django 5.0.3 on 2026-05-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="hf_model_id",
            field=models.CharField(
                blank=True,
                help_text="Например: HuggingFaceH4/zephyr-7b-beta",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="endpoint_url",
            field=models.URLField(
                help_text="Например: https://router.huggingface.co/v1/chat/completions"
            ),
        ),
    ]
